spring.application.name=demo
server.error.include-message=never
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB
telegram-drive.session-root=./telegram-drive-data/sessions
telegram-drive.upload-root=./telegram-drive-data/staging
